/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED01_aliases.h"
#include "LED01.h"
#include "LED02_aliases.h"
#include "LED02.h"
#include "LEFT_aliases.h"
#include "LEFT.h"
#include "TOP_aliases.h"
#include "TOP.h"
#include "LED03_aliases.h"
#include "LED03.h"
#include "LED04_aliases.h"
#include "LED04.h"
#include "DOWN_aliases.h"
#include "DOWN.h"
#include "RIGHT_aliases.h"
#include "RIGHT.h"
#include "LCD.h"
#include "ROW0_aliases.h"
#include "ROW0.h"
#include "ROW1_aliases.h"
#include "ROW1.h"
#include "ROW2_aliases.h"
#include "ROW2.h"
#include "ROW3_aliases.h"
#include "ROW3.h"
#include "COL1_aliases.h"
#include "COL1.h"
#include "COL2_aliases.h"
#include "COL2.h"
#include "COL3_aliases.h"
#include "COL3.h"
#include "POT_aliases.h"
#include "POT.h"
#include "ADC.h"
#include "Photores_aliases.h"
#include "Photores.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

